// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Jaxp3zgVasFsxNF7J0ehQJ3qErkL4SY',
    appId: '1:586807645396:web:f4cfaa209a0e20a4ddd741',
    messagingSenderId: '586807645396',
    projectId: 'street-scan',
    authDomain: 'street-scan.firebaseapp.com',
    storageBucket: 'street-scan.firebasestorage.app',
    measurementId: 'G-83P4D2D89X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlufOx1VFetU5ULR2aiDpIQt-Caee3xMY',
    appId: '1:586807645396:android:aca7956285ee3772ddd741',
    messagingSenderId: '586807645396',
    projectId: 'street-scan',
    storageBucket: 'street-scan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXJtePrJU7gQExC8jI478FbswnttV3yGM',
    appId: '1:586807645396:ios:2a96c39466e1cecaddd741',
    messagingSenderId: '586807645396',
    projectId: 'street-scan',
    storageBucket: 'street-scan.firebasestorage.app',
    iosBundleId: 'com.streetscan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXJtePrJU7gQExC8jI478FbswnttV3yGM',
    appId: '1:586807645396:ios:2a96c39466e1cecaddd741',
    messagingSenderId: '586807645396',
    projectId: 'street-scan',
    storageBucket: 'street-scan.firebasestorage.app',
    iosBundleId: 'com.streetscan.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Jaxp3zgVasFsxNF7J0ehQJ3qErkL4SY',
    appId: '1:586807645396:web:da32a13826df2370ddd741',
    messagingSenderId: '586807645396',
    projectId: 'street-scan',
    authDomain: 'street-scan.firebaseapp.com',
    storageBucket: 'street-scan.firebasestorage.app',
    measurementId: 'G-33K1Q581FW',
  );
}
